# Generated by Django 3.0.8 on 2020-07-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishedAt', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('videoId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideoThumbails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('default', 'default'), ('medium', 'medium'), ('high', 'high'), ('standard', 'standard'), ('maxres', 'maxres')], default='default', max_length=20)),
                ('url', models.URLField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('youtubeVideoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.YoutubeVideo')),
            ],
        ),
    ]
