# Generated by Django 3.0.8 on 2020-07-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='videoId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubevideothumbails',
            name='youtubeVideoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='youtube.YoutubeVideo'),
        ),
    ]
