# Generated by Django 3.0.8 on 2020-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200712_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startFromPublishedAt', models.DateTimeField()),
            ],
        ),
    ]
